### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MaxKman** [HelenaLC/muscat#6]
Hi,

thanks so much for providing this alongside the great paper!

The installation of the current master fails with

> ** testing if installed package can be loaded from temporary location
> Error: package or namespace load failed for ‘muscat’ in namespaceExport(ns, exports):
>  undefined exports: simData2
> Error: loading failed
> Execution halted
> ERROR: loading failed

in my hands. The developer version installs without problem. Let me know if you need more information.

Best Max

**Comment by HelenaLC** [comment]
Thank you! It's fixed now; sorry about that!

**Comment by MaxKman** [comment]
Thanks for the quick response! I tried again but still get the same error.

Best Max
